name: Terraform Apply

on:
  workflow_dispatch:
  push:
    branches: [develop]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    environment: terraform
    name: Run Terraform Apply
    if: github.event.head_commit.message != 'skip apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::601920909369:role/aws-actions
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Update kubeconfig (EKS)
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name tech-challenge-cluster

      - name: Wait for EKS API
        run: |
          for i in {1..30}; do
            kubectl get ns >/dev/null 2>&1 && exit 0
            echo "Waiting for EKS..."
            sleep 10
          done
          exit 1

      - name: Apply aws-auth ConfigMap
        run: kubectl apply -f infra/k8s/aws-auth.yaml
