name: Terraform Apply

on:
  workflow_dispatch:
  push:
    branches:
      - develop   # ou main, se preferirem aplicar em produção

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    environment: terraform
    name: Run Terraform Apply
    if: github.event.head_commit.message != 'skip apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::601920909369:role/aws-actions
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
